# Generated by Django 3.0.8 on 2020-07-30 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='subject',
        ),
    ]
