# Generated by Django 3.0.8 on 2020-07-30 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_remove_unit_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject_unit', to='schoolapp.Subject'),
            preserve_default=False,
        ),
    ]
