# Generated by Django 3.0.8 on 2020-08-10 10:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/videos/%Y/%m/%d/'),
        ),
    ]
