# Generated by Django 3.0.8 on 2020-08-19 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0008_auto_20200815_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='combination',
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_level', to='schoolapp.Level'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='NULL', max_length=255),
        ),
    ]
