# Generated by Django 3.0.8 on 2020-08-19 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0009_auto_20200819_2013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Combination',
        ),
    ]
