# Generated by Django 3.0.8 on 2020-08-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_delete_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='students_subjects', to='schoolapp.Student'),
        ),
    ]
